// Load the stage loader utility
def stageLoader = load 'loadStages.groovy'

pipeline {
    agent {
        kubernetes {
            yaml file('pod-template.yaml')
        }
    }

    environment {
        AWS_REGION = 'us-east-1'
        ECR_REGISTRY = '773893527461.dkr.ecr.us-east-1.amazonaws.com'
        ECR_REPOSITORY = 'node-app-jenkins'
        TARGET_FOLDER = 'nodeapp'
    }

    triggers {
        githubPush()
    }

    stages {
        stage('Initialize') {
            steps {
                script {
                    // Load all stages
                    stageLoader.loadStages()
                }
            }
        }
    }
}