// Jenkinsfile
@Library('shared-library') _

def envVars = load 'environment.groovy'

pipeline {
  agent {
    kubernetes {
      yaml file('pod-template.yaml')
    }
  }

  environment {
    AWS_REGION = envVars.AWS_REGION
    ECR_REGISTRY = envVars.ECR_REGISTRY
    ECR_REPOSITORY = envVars.ECR_REPOSITORY
    TARGET_FOLDER = envVars.TARGET_FOLDER
  }

  triggers {
    githubPush()
  }

  stages {
    stage('Checkout') {
      steps {
        script {
          checkoutStage()
        }
      }
    }

    stage('Build & Scan') {
      steps {
        script {
          buildScanStage()
        }
      }
    }

    stage('Push to ECR') {
      steps {
        script {
          pushEcrStage()
        }
      }
    }

    stage('Notify') {
      steps {
        script {
          notifyStage()
        }
      }
    }
  }
}